- name: darkmodebuddy | Install DarkModeBuddy
  homebrew_cask:
    name: darkmodebuddy
    state: present

- name: darkmodebuddy | Configure DarkModeBuddy darkness threshold
  community.general.osx_defaults:
    domain: codes.rambo.DarkModeBuddy
    key: darknessThreshold
    type: float
    value: 29.82

- name: darkmodebuddy | Enable DarkModeBuddy auto-switch
  community.general.osx_defaults:
    domain: codes.rambo.DarkModeBuddy
    key: isChangeSystemAppearanceBasedOnAmbientLightEnabled
    type: bool
    value: true
