- name: cron - Update Homebrew packages
  ansible.builtin.cron:
    name: "update_homebrew"
    special_time: daily
    job: "/opt/homebrew/bin/brew update && /opt/homebrew/bin/brew upgrade && /opt/homebrew/bin/brew cleanup"
