- name: Disable press-and-hold for accented characters
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: ApplePressAndHoldEnabled
    type: bool
    value: false

- name: Set fast key repeat rate
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: KeyRepeat
    type: float
    value: 2

- name: Set short delay until key repeat
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: InitialKeyRepeat
    type: float
    value: 15
