- name: insync | Import Insync GPG key
  become: true
  rpm_key:
    key: https://d2t3ff60b2tol4.cloudfront.net/repomd.xml.key

- name: insync | Create insync.repo
  become: true
  copy:
    dest: /etc/yum.repos.d/insync.repo
    content: |
      [insync]
      name=insync repo
      baseurl=http://yum.insync.io/fedora/$releasever/
      gpgcheck=1
      gpgkey=https://d2t3ff60b2tol4.cloudfront.net/repomd.xml.key
      enabled=1
      metadata_expire=120m
    owner: root
    group: root
    mode: '0644'

- name: insync | Install Insync
  become: true
  package:
    name: insync
    state: present
