- name: neovim | Enable lazygit COPR
  become: true
  command: dnf copr enable atim/lazygit -y
  args:
    creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:atim:lazygit.repo

- name: neovim | Install Neovim
  become: true
  package:
    name:
      - neovim
      - fd-find
      - lazygit
      - ripgrep
      - fzf
    state: present
