- name: Create the `aur_builder` user
  become: yes
  ansible.builtin.user:
    name: aur_builder
    create_home: yes
    group: wheel
- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: yes
    mode: 0644
    validate: "visudo -cf %s"

- name: Install bc
  become: true
  package:
    name: bc

- name: Install cronie
  pacman:
    name: cronie
- name: Enable cronie service
  systemd:
    name: cronie
    enabled: true
    state: started

- name: Install SimpleScan
  become: true
  package:
    name: simple-scan

- name: Install paru
  become: true
  package:
    name: paru

- name: Enable bluetooth service
  become: true
  systemd:
    name: bluetooth.service
    enabled: yes
    state: started
