- name: docker | Install Docker
  become: true
  package:
    name:
      - docker
      - docker-compose
    state: present

- name: docker | Enable Docker service
  become: true
  systemd:
    name: docker
    enabled: true
    state: started
