- name: fonts | Install JetBrainsMono Nerd Font
  become: true
  package:
    name: ttf-jetbrains-mono-nerd
    state: present

- name: fonts | Install Inter font
  become: true
  package:
    name: inter-font
    state: present

- name: fonts | Install Roboto font
  become: true
  package:
    name: ttf-roboto
    state: present

- name: fonts | Install Noto fonts
  become: true
  package:
    name:
      - noto-fonts
      - noto-fonts-cjk
      - noto-fonts-extra
    state: present

- name: fonts | Install Microsoft core fonts (AUR)
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name: ttf-ms-fonts
