- name: reflector | Install reflector
  become: true
  package:
    name: reflector
    state: present

- name: reflector | Configure reflector
  become: true
  copy:
    content: |
      --save /etc/pacman.d/mirrorlist
      --protocol https
      --latest 10
      --sort rate
    dest: /etc/xdg/reflector/reflector.conf
    owner: root
    group: root
    mode: "0644"

- name: reflector | Enable reflector timer (weekly mirror update)
  become: true
  systemd:
    name: reflector.timer
    enabled: true
    state: started
