- name: Enable multilib repository
  become: true
  blockinfile:
    path: /etc/pacman.conf
    marker: "# {mark} ANSIBLE MANAGED - multilib"
    block: |
      [multilib]
      Include = /etc/pacman.d/mirrorlist
  register: multilib_result

- name: Update pacman cache after enabling multilib
  become: true
  pacman:
    update_cache: true
  when: multilib_result.changed

- name: Install Steam
  become: true
  package:
    name: steam
