- import_tasks: tasks/linux/fastfetch.yml
- import_tasks: tasks/linux/gimp.yml
- import_tasks: tasks/linux/gnome.yml
- import_tasks: tasks/linux/htop.yml
- import_tasks: tasks/linux/insync.yml
- import_tasks: tasks/linux/zoxide.yml
- import_tasks: tasks/linux/zsh.yml

- import_tasks: tasks/linux/cron/cleanup.yml
- import_tasks: tasks/linux/cron/dark-mode.yml
- import_tasks: tasks/linux/cron/next-wallpaper.yml
- import_tasks: tasks/linux/cron/update_cursor.yml
