- name: zsh | Install Zsh
  become: true
  package:
    name: zsh
    state: present

- name: zsh | Set Zsh as default shell
  become: true
  user:
    name: "{{ lookup('env', 'USER') }}"
    shell: /bin/zsh
