- name: flatpak | Install Flatpak
  become: true
  apt:
    name: flatpak
    state: present

- name: flatpak | Add Flathub remote
  become: true
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
