- name: vscode | Add Microsoft signing key
  become: true
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /etc/apt/keyrings/packages.microsoft.asc
    mode: '0644'

- name: vscode | Add VS Code repository
  become: true
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64 signed-by=/etc/apt/keyrings/packages.microsoft.asc] https://packages.microsoft.com/repos/code stable main'
    filename: vscode
    state: present

- name: vscode | Install Visual Studio Code
  become: true
  apt:
    name: code
    state: present
    update_cache: true
